- name: make bash profile
  sudo: true
  template:
    src: bash_profile.j2
    dest: "/home/{{ ansible_ssh_user }}/.bash_profile"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0600
    backup: yes
  tags:
    - make_bash_profile
