- name: restart machine?
  stat:
    path: /var/run/reboot-required
  register: reboot
  tags:
    - restart

- name: restart machine
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: reboot.stat.exists == true
  tags:
    - restart

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started
  sudo: false
  when: reboot.stat.exists == true
  tags:
    - restart




