- name: Install nginx
  sudo: true
  apt: name=nginx state=present
  tags:
    - nginx

- name: Start and enable nginx
  service: name=nginx state=started enabled=yes
  tags:
    - nginx

- include: configure_nginx.yml
