# handlers are only fired when certain tasks report changes, and are run at the end of each play
- name: restart nginx
  sudo: true
  service: name=nginx state=restarted

- name: restart monit
  sudo: true
  service: name=monit state=restarted
